apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rxjepgtdn-nodejs 
  janus-idp.io/tekton: rxjepgtdn-nodejs
  backstage.io/kubernetes-id: rxjepgtdn-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rxjepgtdn-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml